/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Feb 28 01:59:39 GMT 2020
 */

package org.apache.log4j;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class FileAppender_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.log4j.FileAppender"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/9c/2fm2fk412pj9zjkzvdx9w2fr0000gn/T/"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/Users/joaocorreia/log4j"); 
    java.lang.System.setProperty("user.home", "/Users/joaocorreia"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "joaocorreia"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
    java.lang.System.setProperty("log4j.configuration", "SUT.log4j.properties"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(FileAppender_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.log4j.helpers.OnlyOnceErrorHandler",
      "org.apache.log4j.spi.OptionHandler",
      "org.apache.log4j.SimpleLayout",
      "org.apache.log4j.spi.ErrorHandler",
      "org.apache.log4j.spi.LoggingEvent",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.apache.log4j.AppenderSkeleton",
      "org.apache.log4j.spi.Filter",
      "org.apache.log4j.DailyRollingFileAppender",
      "org.apache.log4j.Logger",
      "org.apache.log4j.Appender",
      "org.apache.log4j.Priority",
      "org.apache.log4j.RollingCalendar",
      "org.apache.log4j.Level",
      "org.apache.log4j.spi.Configurator",
      "org.apache.log4j.FileAppender",
      "org.apache.log4j.WriterAppender",
      "org.apache.log4j.Layout",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.QuietWriter",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.Category"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.log4j.Layout", false, FileAppender_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(FileAppender_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.log4j.AppenderSkeleton",
      "org.apache.log4j.WriterAppender",
      "org.apache.log4j.FileAppender",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.helpers.OnlyOnceErrorHandler",
      "org.apache.log4j.helpers.QuietWriter",
      "org.apache.log4j.spi.LoggingEvent",
      "org.apache.log4j.Layout",
      "org.apache.log4j.Level",
      "org.apache.log4j.Priority",
      "org.apache.log4j.spi.Filter",
      "org.apache.log4j.DailyRollingFileAppender",
      "org.apache.log4j.RollingCalendar",
      "org.apache.log4j.RollingFileAppender",
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "org.apache.log4j.AsyncAppender",
      "org.apache.log4j.helpers.AppenderAttachableImpl",
      "org.apache.log4j.AsyncAppender$Dispatcher",
      "org.apache.log4j.helpers.CountingQuietWriter",
      "org.apache.log4j.varia.DenyAllFilter",
      "org.apache.log4j.helpers.DateLayout",
      "org.apache.log4j.TTCCLayout",
      "org.apache.log4j.helpers.RelativeTimeDateFormat",
      "org.apache.log4j.EnhancedPatternLayout",
      "org.apache.log4j.EnhancedMyPatternLayout",
      "org.apache.log4j.helpers.PatternParser",
      "org.apache.log4j.MyPatternParser",
      "org.apache.log4j.helpers.FormattingInfo",
      "org.apache.log4j.helpers.PatternConverter",
      "org.apache.log4j.helpers.PatternParser$BasicPatternConverter",
      "org.apache.log4j.helpers.PatternParser$LiteralPatternConverter",
      "org.apache.log4j.EnhancedPatternLayoutTest$DerivedPatternLayout",
      "org.apache.log4j.pattern.BridgePatternParser",
      "org.apache.log4j.pattern.BridgePatternConverter",
      "org.apache.log4j.pattern.PatternConverter",
      "org.apache.log4j.pattern.LoggingEventPatternConverter",
      "org.apache.log4j.pattern.NamePatternConverter",
      "org.apache.log4j.pattern.NameAbbreviator$NOPAbbreviator",
      "org.apache.log4j.pattern.NameAbbreviator",
      "org.apache.log4j.pattern.LoggerPatternConverter",
      "org.apache.log4j.pattern.ClassNamePatternConverter",
      "org.apache.log4j.pattern.DatePatternConverter",
      "org.apache.log4j.pattern.FileLocationPatternConverter",
      "org.apache.log4j.pattern.FullLocationPatternConverter",
      "org.apache.log4j.pattern.LineLocationPatternConverter",
      "org.apache.log4j.pattern.MessagePatternConverter",
      "org.apache.log4j.pattern.LineSeparatorPatternConverter",
      "org.apache.log4j.pattern.MethodLocationPatternConverter",
      "org.apache.log4j.pattern.LevelPatternConverter",
      "org.apache.log4j.pattern.RelativeTimePatternConverter",
      "org.apache.log4j.pattern.ThreadPatternConverter",
      "org.apache.log4j.pattern.NDCPatternConverter",
      "org.apache.log4j.pattern.PropertiesPatternConverter",
      "org.apache.log4j.pattern.SequenceNumberPatternConverter",
      "org.apache.log4j.pattern.ThrowableInformationPatternConverter",
      "org.apache.log4j.pattern.PatternParser$ReadOnlyMap",
      "org.apache.log4j.pattern.FileDatePatternConverter",
      "org.apache.log4j.pattern.IntegerPatternConverter",
      "org.apache.log4j.pattern.PatternParser",
      "org.apache.log4j.pattern.FormattingInfo",
      "org.apache.log4j.SimpleLayout",
      "org.apache.log4j.PatternLayout",
      "org.apache.log4j.MyPatternLayout",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.helpers.NullEnumeration",
      "org.apache.log4j.spi.ThrowableInformation",
      "org.apache.log4j.HTMLLayout",
      "org.apache.log4j.varia.LevelMatchFilter",
      "org.apache.log4j.pattern.LiteralPatternConverter",
      "org.apache.log4j.VectorErrorHandler",
      "org.apache.log4j.PatternLayoutTest$DerivedPatternLayout",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.spi.RootLogger",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.MyPatternParser$UserDirPatternConverter",
      "org.apache.log4j.ProvisionNode",
      "org.apache.log4j.ConsoleAppender",
      "org.apache.log4j.spi.LocationInfo",
      "org.apache.log4j.varia.LevelRangeFilter",
      "org.apache.log4j.spi.NOPLoggerRepository",
      "org.apache.log4j.spi.NOPLogger",
      "org.apache.log4j.helpers.PatternParser$NamedPatternConverter",
      "org.apache.log4j.helpers.PatternParser$CategoryPatternConverter",
      "org.apache.log4j.helpers.ThreadLocalMap",
      "org.apache.log4j.MDC",
      "org.apache.log4j.DefaultThrowableRenderer",
      "org.apache.log4j.helpers.Transform",
      "org.apache.log4j.varia.StringMatchFilter",
      "org.apache.log4j.helpers.PatternParser$MDCPatternConverter",
      "org.apache.log4j.NDC"
    );
  }
}
